### ISSUE TITLE
Branch.h missing

### ISSUE THREAD

**Issue by kashif-imagyn** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#604]
i have the plugin by running command cordova plugin add 
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution
its working in android but in ios i am getting this error
i have install the branch framework using pod and added in project from xcode

1 error generated.

CompileC /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Objects-normal/x86_64/AppDelegate+BranchSdk.o Jazeel/Plugins/branch-cordova-sdk/AppDelegate+BranchSdk.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/macsystem/Desktop/waqfee/platforms/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/macsystem/Desktop/waqfee/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Users/macsystem/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios10.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/macsystem/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/macsystem/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Wunreachable-code -Wno-implicit-atomic-properties -Wno-objc-interface-ivars -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DCOCOAPODS=1 -DGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1 -DPB_FIELD_32BIT=1 -DPB_NO_PACKED_STRUCTS=1 -DPB_ENABLE_MALLOC=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Index/DataStore -iquote /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Jazeel-generated-files.hmap -I/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Jazeel-own-target-headers.hmap -I/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Jazeel-all-non-framework-target-headers.hmap -ivfsoverlay /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/all-product-headers.yaml -iquote /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Jazeel-project-headers.hmap -I/Users/macsystem/Desktop/waqfee/platforms/ios/build/emulator/include -I/Users/macsystem/Desktop/waqfee/platforms/ios/build/emulator/usr/local/lib/include -I/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/UninstalledProducts/include -I/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/UninstalledProducts/iphonesimulator/include -I/Users/macsystem/Desktop/waqfee/platforms/ios/build/emulator -I/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/DerivedSources-normal/x86_64 -I/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/DerivedSources/x86_64 -I/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/DerivedSources -F/Users/macsystem/Desktop/waqfee/platforms/ios/build/emulator -F/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/Branch -F/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac -F/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/Protobuf -F/Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/nanopb -F/Users/macsystem/Desktop/waqfee/platforms/ios/Pods/FirebaseAnalytics/Frameworks -F/Users/macsystem/Desktop/waqfee/platforms/ios/Pods/FirebaseCore/Frameworks -F/Users/macsystem/Desktop/waqfee/platforms/ios/Pods/FirebaseInstanceID/Frameworks -F/Users/macsystem/Desktop/waqfee/platforms/ios/Pods/FirebaseMessaging/Frameworks -FJazeel/Plugins/blinkid-cordova -FJazeel/Plugins/com.googlemaps.ios -FJazeel/Plugins/com.vidyo.plugin -FJazeel/Plugins/cordova-plugin-facebook4 -FJazeel/Plugins/cordova-plugin-googleplus -iquote /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/Branch/Branch.framework/Headers -iquote /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac/GoogleToolboxForMac.framework/Headers -iquote /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/Protobuf/Protobuf.framework/Headers -iquote /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Products/Debug-iphonesimulator/nanopb/nanopb.framework/Headers -include /Users/macsystem/Desktop/waqfee/platforms/ios/build/sharedpch/Jazeel-Prefix-fhtszzduwrqttcazoosvjmobnbvu/Jazeel-Prefix.pch -MMD -MT dependencies -MF /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Objects-normal/x86_64/AppDelegate+BranchSdk.d --serialize-diagnostics /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Objects-normal/x86_64/AppDelegate+BranchSdk.dia -c /Users/macsystem/Desktop/waqfee/platforms/ios/Jazeel/Plugins/branch-cordova-sdk/AppDelegate+BranchSdk.m -o /Users/macsystem/Library/Developer/Xcode/DerivedData/Jazeel-cdwvcdltljnwctftqveilttxzplx/Build/Intermediates.noindex/Jazeel.build/Debug-iphonesimulator/Jazeel.build/Objects-normal/x86_64/AppDelegate+BranchSdk.o
/Users/macsystem/Desktop/waqfee/platforms/ios/Jazeel/Plugins/branch-cordova-sdk/AppDelegate+BranchSdk.m:6:9: fatal error: 'Branch.h' file not found
#import "Branch.h"
        ^~~~~~~~~~
please help me

**Comment by caleb87** [comment]
I have the same issue.

**Comment by rikycg** [comment]
I have the same issue

**Comment by chrhenne** [comment]
I have the same issue as well

**Comment by Zyostes** [comment]
I have the same issue, it prevents Phonegap to build for iOS.

**Comment by johanrd** [comment]
This also prevents cordova to build on iOS for us.

**Comment by jcancinar** [comment]
Hey guys, I have solved my issue.

I have removed "**cordova-plugin-inappbrowser**" (v3.0.0) and it magically worked.

----

Backstory:
- When I tried with a fresh cordova project, this cordova plugin of Branch worked
- So I decided to find out which plugin was causing the problem.
- cordova-plugin-inappbrowser@3.0.0 works fine on its own but not together with branch-cordova-sdk

**Comment by front-stream** [comment]
I have the same issue.

**Comment by tommymetz** [comment]
same

**Comment by jcancinar** [comment]
@front-stream @tommymetz Have you tried my solution?

**Comment by front-stream** [comment]
@jcancinar yes, without success :/

**Comment by tommymetz** [comment]
@jcancinar we don't use that plugin.

**Comment by chrhenne** [comment]
When trying to make a minimal reproducible case for this, I found that removing the branch plugin did not solve the issue. I then got a similar error for a different plugin. I finally solved the issue by upgrading the phonegap-plugin-push plugin from 2.2.3 to 2.3.0 (and reinstalling everything from repo). So, I believe the "'Branch.h' file not found" error was simply the first symptom that there was an issue with the project in general. In other words, the Branch plugin seems to just be the unlucky first plugin to fail.

**Comment by kashif-imagyn** [comment]
Problem is solved whene installing Branch framework using cocapods
https://docs.branch.io/apps/ios/

  use_frameworks!

  pod 'Branch'

dont use  use_frameworks! 
then it will work

**Comment by MrPro100** [comment]
@kashif-imagyn Can you explain more, what need change to fix this?

**Comment by subhi-shuqier** [comment]
@kashif-imagyn can you please explain more?

**Comment by tommymetz** [comment]
Just an FYI I recently upgrade to cordova-ios 5.1.0, cordova-android 8.1.0 and branch-cordova-sdk 4.0.0 and I'm no longer seeing this branchio error (although now I'm investigating a different error unrelated to branch).

**Comment by musicbender** [comment]
@tommymetz Unfortunately, this didn't fix the issue for me.

**Comment by kashif-imagyn** [comment]
> @kashif-imagyn can you please explain more?

Open you Pod file and add this
pod 'Branch' 
after this run pod install
pod file is located in platform/ios/

**Comment by chrhenne** [comment]
Upgrading and re-installing all cordova plugins resolved the issue for me. And make sure you have the same target under `Target > Deployment Info` and `Project > Deployment target`.

**Comment by subhi-shuqier** [comment]
Please any updates here? can anyone help?
@kashif-imagyn I am developing ionic 4 application, I tried to add pod 'Branch' to my pod file as follows:
1-  run "ionic cordova build ios --prod --release --buildFlag='-UseModernBuildSystem=0'"
2- cd platforms/ios
3- pod install
4- add "pod 'Branch'" to pod file
5- pod install
Error appears "The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation." I tired to solve this issue following this [link](https://stackoverflow.com/questions/21366549/error-the-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-re) with no luck.

Can you please advise?

**Comment by codinronan** [comment]
Hi all ok so yes I could repro this and it was a combination of 3 things:

1. branch sdk version
2. cordova-ios version 
3. any build error in any pod will also cause it (because Branch is usually the first Pod, so it will come first alphabetically after the main project attempts to resolve Pod dependencies)

The next version we're releasing addresses the first two and for now is free of build issues.

**Comment by echo-branch** [comment]
This should be resolved in the latest release.
