### ISSUE TITLE
Android - Upgrading to 3.1.6 doesn't build anymore (Branch.aar not loaded)

### ISSUE THREAD

**Issue by Unibozu** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#558]
Hi,

We've noticed an issue with Android from version 3.1.6 (which was unintentionally upgraded during our work). It appears the `Branch.aar` isn't located in the right place anymore.

From what I've found the file is copied to `app/libs` however Gradle isn't looking in this directory. Manually copying the file onto `libs` solve the issue.

Recent changes to the build configuration might cause this: https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/7df49cb0ee351a6faa6eddf052464167baedf4a8

Error examples:

```
app/platforms/android/src/io/branch/BranchSDK.java:21: error: package io.branch.indexing does not exist
import io.branch.indexing.BranchUniversalObject;
app/platforms/android/src/io/branch/BranchSDK.java:31: error: package io.branch.referral.util does not exist
import io.branch.referral.util.ProductCategory;
...
```

Thanks

**Comment by echo-branch** [comment]
Hi,

I've been unable to repro this exact issue.  Could you tell us which version you're upgrading from and what command you use to build and run your project?  There may be an issue with our switch from jar to aar.

Thanks

**Comment by Unibozu** [comment]
Hi,

After a few tests, I can confirm it works with `cordova-android@7.1.4` but not with `cordova-android@6.4.0`. I've simply created an empty cordova app, added cordova-android 6.4 and your plugin to reproduce it.

Hope this helps

**Comment by masimplo** [comment]
Same issue here running cordova-android@6.4.0

**Comment by echo-branch** [comment]
Thanks Unibozu!  

I've created a ticket for this sprint to look into this issue.

**Comment by csalmi-branch** [comment]
@Unibozu, can you give us a bit more information about your configuration? What version of Cordova are you using, gradle version, android sdk version, etc.? 

We are investigating this issue, but with all of the different interdependencies, its hard to know exactly what will fix the problem in this scenario. A fix for Cordova 7 is different than a fix for Cordova 9.

**Comment by Unibozu** [comment]
Hi csalmi,

Sure - see below:

cordova: 8.1.2
cordova-android: 6.4.0
gradle: 4.1.0 (version from `platforms/android/build.gradle`)
cordova-branch-sdk: 3.1.6
android-sdk: 8.0 API 26

The only thing I understand at the moment is that the issue happens with `cordova-android` 6 and not with 7, as isolated during a test.

Our cordova application has many plugins and we don't update cordova

**Comment by adrianyg7** [comment]
Solved on https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution/pull/562

**Comment by echo-branch** [comment]
This should be resolved in the latest release.

**Comment by Unibozu** [comment]
@echo-branch thanks!
